name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      description: What version of `eslint-plugin-testing-library` are you using?
      placeholder: v4.10.1
    validations:
      required: true

  - type: input
    id: eslint_version
    attributes:
      label: ESLint version
      description: What version of ESLint are you using?
      placeholder: v7.31.0
    validations:
      required: true

  - type: input
    id: node_js_version
    attributes:
      label: Node.js version
      description: What version of Node.js are you using?
      placeholder: 14.17.3
    validations:
      required: true

  - type: input
    id: npm_yarn_version
    attributes:
      label: npm/yarn version
      description: Tell us whether you use npm or yarn as your package manager, and what version.
      placeholder: npm 6.14.13
    validations:
      required: true

  - type: input
    id: operating_system
    attributes:
      label: Operating system
      description: Tell us what operating system you use, and what version.
      placeholder: macOS Big Sur, version 11.4
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug description
      description: Describe the bug at a high level.
      placeholder: I was doing ..., but I expected ...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Give us a ordered list of the steps to reproduce the problem.
      placeholder: |
        1. Go to ...
        2. Do ....
        3. See bug
    validations:
      required: true

  - type: textarea
    id: error_output_screenshots
    attributes:
      label: Error output/screenshots
      description: Copy/paste any error messages or helpful screenshots into this field.
      placeholder: 'Tip: you can copy/paste error messages in here. You can click and drag screenshots into this field.'
    validations:
      required: false

  - type: textarea
    id: eslint_config
    attributes:
      label: ESLint configuration
      description: Copy/paste your ESLint configuration into this field.
      placeholder: 'Tip: you can find your ESLint configuration in the `.eslintrc` file.'
    validations:
      required: true

  - type: textarea
    id: rule_affected
    attributes:
      label: Rule(s) affected
      description: Tell us what `eslint-pluging-testing-library` rule(s) are affected by this bug.
      placeholder: 'Tip: check your `.eslintrc` for rules.'
    validations:
      required: true

  - type: textarea
    id: anything_else
    attributes:
      label: Anything else?
      description: If there's anything else we need to know, tell us about it here.
      placeholder: By the way, you also need to know about...
    validations:
      required: true

  - type: dropdown
    id: want_to_submit_pr_to_fix_bug
    attributes:
      label: Do you want to submit a pull request to fix this bug?
      options:
        - 'Yes'
        - 'Yes, but need help'
        - 'No'
    validations:
      required: true
