import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import * as prettier from 'prettier';

import type { TSESLint } from '@typescript-eslint/utils';

const __dirname = new URL('.', import.meta.url).pathname;

const addAutoGeneratedComment = (code: string) =>
	[
		'// THIS CODE WAS AUTOMATICALLY GENERATED',
		'// DO NOT EDIT THIS CODE BY HAND',
		'// YOU CAN REGENERATE IT USING pnpm run generate:configs',
		'',
		code,
	].join('\n');

/**
 * Helper function writes configuration.
 */
export const writeConfig = async (
	config: TSESLint.Linter.ConfigType,
	configName: string
): Promise<void> => {
	const code = `import type { Linter } from 'eslint';

	export default ${JSON.stringify(config)} satisfies Linter.LegacyConfig;
	`;

	const prettierConfig = await prettier.resolveConfig(__dirname);
	const configStr = await prettier.format(addAutoGeneratedComment(code), {
		parser: 'typescript',
		...prettierConfig,
	});
	const filePath = resolve(__dirname, `../../src/configs/${configName}.ts`);

	await writeFile(filePath, configStr);
};
