name: CI

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validations:
    name: Run validations
    uses: ./.github/workflows/verifications.yml

  required-checks:
    name: Require CI status checks
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && github.event.action != 'closed' }}
    needs: [validations]
    steps:
      - run: ${{ !contains(needs.*.result, 'failure') }}
      - run: ${{ !contains(needs.*.result, 'cancelled') }}
