name: Smoke test

on:
  schedule: # Every Sunday at midnight
    - cron: '0 0 * * SUN'
  workflow_dispatch: # Manual trigger
  release:
    types: [published]

permissions:
  issues: write # To create issues for test results

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0

      - name: Use Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - run: |
          pnpm install
          pnpm run build

      - uses: AriPerkkio/eslint-remote-tester-run-action@5724813c126b48e735e7fc08f048f318c3df262d # v5
        with:
          issue-title: 'Results of smoke test'
          issue-label: 'smoke-test'
          eslint-remote-tester-config: eslint-remote-tester.config.ts
